name: Checking for focused specs

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'

jobs:
  check-focus-target:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Running the focus check script
        run: |
          grep -ErnI --include="*.go" 'FIt|FDescribe|FContext|FWhen|FEntry|FDescribeTable' ./hosted && exit 1 || echo "No focused specs found." && exit 0
