name: Rancher Upgrade
run-name: [${{ inputs.hosted_provider }}] Upgrade Rancher ${{ inputs.rancher_version }} to ${{ inputs.upgrade_rancher_version }}

on:
  workflow_dispatch:
    inputs:
      k3s_version:
        description: k3s version of local cluster
        required: true
        type: string
        default: v1.28.9+k3s1
      rancher_version:
        description: Rancher version to deploy; it should be released version; supported formats - 2.9.0, 2.9.0-rc1
        required: true
        type: string
      upgrade_rancher_version:
        description: Rancher version to upgrade; supported formats - 2.9.0, 2.9.0-rc1, devel/2.9
        required: true
        type: string
      hosted_provider:
        description: Hosted Provider to test
        type: choice
        options:
          - gke
          - eks
          - aks
      downstream_cluster_cleanup:
        type: boolean
        default: true
        description: Cleanup downstream cluster
      rancher_channel:
        description: Release channel to use for testing (stable/latest/alpha)
        default: latest
        type: string
      downstream_k8s_minor_version:
        description: Downstream cluster minor K8s version to test (e.g. 1.28)
        required: true
        type: string
      downstream_k8s_upgrade_minor_version:
        description: Downstream cluster minor k8s version to upgrade (e.g. 1.29)
        type: string
        required: true
      destroy_runner:
        description: Destroy the auto-generated self-hosted runner
        default: true
        type: boolean

jobs:
  e2e:
    uses: ./.github/workflows/main.yaml
    secrets: inherit
    with:
      hosted_provider: ${{ inputs.hosted_provider }}
      rancher_version: ${{ inputs.rancher_version }}
      rancher_upgrade_version: ${{ inputs.upgrade_rancher_version}}
      k3s_version: ${{ inputs.k3s_version}}
      operator_nightly_chart: false
      tests_to_run: 'rancher_upgrade'
      destroy_runner: ${{ inputs.destroy_runner == true }}
      runner_template: 'hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v2'
      downstream_k8s_minor_version: ${{ inputs.downstream_k8s_minor_version }}
      downstream_k8s_upgrade_minor_version: ${{ inputs.downstream_k8s_upgrade_minor_version }}
      rancher_installed: 'hostname/password'
      downstream_cluster_cleanup: ${{ inputs.downstream_cluster_cleanup == true }}
      rancher_channel: ${{ inputs.rancher_channel }}
